### ISSUE TITLE
Выбивает ошибку 403

### ISSUE THREAD

**Issue by maxsalzberg** [ar1ocker/Squad-Discord-Info#1]

**Comment by maxsalzberg** [comment]
Bot is now running. Press CTRL-C to exit.
Ошибка при получении информации из Battlemetrics,  status code is not 200, 403

**Comment by ar1ocker** [comment]
Battlemetrics тебя почему-то не хочет пускать к своему api

Посмотри вывод команды

```sh
curl "https://api.battlemetrics.com/servers/11122255?fields\[server\]=players,maxPlayers,details"
```

Либо если запускаешь из под Windows просто зайди на https://api.battlemetrics.com/servers/11122255?fields[server]=players,maxPlayers,details

**Comment by maxsalzberg** [comment]
Оказалось что айпи сервера с которого посылал запрос в блокировке у Battlemetrics. Если столкнетесь с такой ошибкой, напишите мейл staff@battlemetrics.com и уточните находится ли ваш айпи в бане.
